/**
 * Admin authentication.
 *
 * This used to be `x-admin-demo: true` — a header anyone could set. It sat on
 * a live domain in front of what was meant to become the customer list.
 *
 * Now: one password, hashed with scrypt, kept in the server's environment and
 * never in this repository (which is public). A successful login returns a
 * signed cookie that carries its own expiry, so no session store is needed and
 * a restart does not sign anyone out mid-task.
 */

import {
  createHmac,
  randomBytes,
  scryptSync,
  timingSafeEqual
} from 'node:crypto';

import { config } from '../lib/config.js';
import { fail } from '../lib/http.js';
import { verifyCode } from '../lib/totp.js';

const COOKIE_NAME = 'steinbach_admin';
const SESSION_HOURS = 12;
const SCRYPT_KEYLEN = 64;

/* Brute-force brake. In memory on purpose: losing the counters on a restart
   costs nothing, and an attacker cannot force a restart anyway. */
const attempts = new Map();
const MAX_ATTEMPTS = 8;
const LOCKOUT_MS = 15 * 60 * 1000;

export function isAdminConfigured() {
  return Boolean(config.adminPasswordHash && config.sessionSecret);
}

/**
 * Is the second step switched on?
 *
 * Deliberately optional. Turning it on is setting ADMIN_TOTP_SECRET; until
 * then the password alone still opens the area, so a half-finished rollout
 * cannot lock the only person with a key out of their own admin area.
 */
export function isSecondFactorConfigured() {
  return Boolean(config.adminTotpSecret);
}

/* A code stays valid for its whole 30-second window, so without this an
   attacker who reads one over a shoulder or off a proxy can use it again a few
   seconds later. In memory like the lockout counters: a restart forgets which
   step was spent, which at worst reopens a window that is about to close by
   itself. */
const spentSteps = new Set();

/**
 * Check the six-digit code, and refuse one that has already been used.
 */
export function verifySecondFactor(code, now = Date.now()) {
  const counter = verifyCode(config.adminTotpSecret, code, now);

  if (counter === null || spentSteps.has(counter)) {
    return false;
  }

  spentSteps.add(counter);

  /* Nothing older than the drift window can be accepted again anyway. */
  const cutoff = Math.floor(now / 1000 / 30) - 2;
  for (const step of spentSteps) {
    if (step < cutoff) {
      spentSteps.delete(step);
    }
  }

  return true;
}

/**
 * Hash format: scrypt$<salt-hex>$<hash-hex>. Generated by
 * `npm run admin-password` — see backend/README.md.
 */
export function hashPassword(password, salt = randomBytes(16).toString('hex')) {
  const derived = scryptSync(String(password), salt, SCRYPT_KEYLEN).toString('hex');
  return `scrypt$${salt}$${derived}`;
}

export function verifyPassword(password, stored) {
  const parts = String(stored || '').split('$');

  if (parts.length !== 3 || parts[0] !== 'scrypt') {
    return false;
  }

  const candidate = Buffer.from(scryptSync(String(password), parts[1], SCRYPT_KEYLEN).toString('hex'), 'utf8');
  const expected = Buffer.from(parts[2], 'utf8');

  if (candidate.length !== expected.length) {
    return false;
  }

  return timingSafeEqual(candidate, expected);
}

/* --------------------------------------------------------------------------
   Rate limiting
   -------------------------------------------------------------------------- */

export function loginBlocked(ip) {
  const entry = attempts.get(ip);

  if (!entry) {
    return false;
  }

  if (Date.now() - entry.first > LOCKOUT_MS) {
    attempts.delete(ip);
    return false;
  }

  return entry.count >= MAX_ATTEMPTS;
}

export function noteFailedLogin(ip) {
  const entry = attempts.get(ip);

  if (!entry || Date.now() - entry.first > LOCKOUT_MS) {
    attempts.set(ip, { count: 1, first: Date.now() });
    return;
  }

  entry.count += 1;
}

export function clearFailedLogins(ip) {
  attempts.delete(ip);
}

/* --------------------------------------------------------------------------
   Session cookie
   -------------------------------------------------------------------------- */

function sign(payload) {
  return createHmac('sha256', config.sessionSecret).update(payload).digest('hex');
}

export function issueSession(response, secure) {
  const expiresAt = Date.now() + SESSION_HOURS * 60 * 60 * 1000;
  const payload = String(expiresAt);
  const value = `${payload}.${sign(payload)}`;

  response.cookie(COOKIE_NAME, value, {
    httpOnly: true,
    sameSite: 'strict',
    secure,
    maxAge: SESSION_HOURS * 60 * 60 * 1000,
    path: '/'
  });
}

export function clearSession(response) {
  response.clearCookie(COOKIE_NAME, { path: '/' });
}

function hasValidSession(request) {
  const raw = request.cookies?.[COOKIE_NAME];

  if (!raw || !config.sessionSecret) {
    return false;
  }

  const separator = raw.lastIndexOf('.');

  if (separator === -1) {
    return false;
  }

  const payload = raw.slice(0, separator);
  const signature = raw.slice(separator + 1);
  const expected = sign(payload);

  if (signature.length !== expected.length) {
    return false;
  }

  if (!timingSafeEqual(Buffer.from(signature, 'utf8'), Buffer.from(expected, 'utf8'))) {
    return false;
  }

  return Number(payload) > Date.now();
}

export function requireAdmin(request, response, next) {
  if (!isAdminConfigured()) {
    return fail(response, 503, 'admin_not_configured',
      'The admin area is not set up on this server. ADMIN_PASSWORD_HASH and SESSION_SECRET are missing.');
  }

  if (!hasValidSession(request)) {
    return fail(response, 401, 'unauthorized', 'Sign in to continue.');
  }

  return next();
}

export { COOKIE_NAME };
